name: "balance-transfer"

x-type: "hlfv1"

description: "Balance Transfer Network"

version: "1.0"

channels:
    mychannel:
        orderers:
            - orderer0.example.com
            - orderer1.example.com
            - orderer2.example.com
        peers:
            peer0.org0.example.com:
                endorsingPeer: true
                chaincodeQuery: true
                ledgerQuery: true
                eventSource: true
            
            peer1.org0.example.com:
                endorsingPeer: false
                chaincodeQuery: true
                ledgerQuery: true
                eventSource: false
            
            peer2.org1.example.com:
                endorsingPeer: true
                chaincodeQuery: true
                ledgerQuery: true
                eventSource: true

            peer3.org1.example.com:
                endorsingPeer: false
                chaincodeQuery: true
                ledgerQuery: true
                eventSource: false

        chaincodes:
            - mycc:v0

organizations:
    Org0:
        mspid: Org0MSP

        peers:
            - peer0.org0.example.com
            - peer1.org0.example.com

        adminPrivateKey:
            path:artifacts/crypto-config/peerOrganizations/org0.example.com/users/Admin@org0.example.com/msp/keystore/26f05334fafcbf833264a1d7f418a70eca4082ccf712f1bca11736e32aaa2d2b_sk
        
        signedCert:
            path: artifacts/crypto-config/peerOrganizations/org0.example.com/users/Admin@org0.example.com/msp/signcerts/Admin@org0.example.com-cert.pem

    Org1:
        mspid: Org1MSP
        
        peers:
            - peer2.org1.example.com
            - peer3.org1.example.com
        
        adminPrivateKey:
            path: artifacts/crypto-config/peerOrganizations/org1.example.com/users/Admin@org1.example.com/msp/keystore/7932bdeb5c1cb47e1bb5cf6c7951ef4b57170d517d24194604b83747802638c8_sk

        signedCert:
            path: artifacts/crypto-config/peerOrganizations/org1.example.com/users/Admin@org1.example.com/msp/signcerts/Admin@org1.example.com-cert.pem

orderers:
    orderer0.example.com:
        url: grpcs://192.168.56.31:7050
        
        grpcOptions:
            ssl-target-name-override: orderer0.example.com

        tlsCACerts:
            path: artifacts/crypto-config/ordererOrganizations/example.com/orderers/orderer0.example.com/tls/ca.crt
    
    orderer1.example.com:
        url: grpcs://192.168.56.41:7050

        grpcOptions:
            ssl-target-name-override: orderer1.example.com

        tlsCACerts:
            path: artifacts/crypto-config/ordererOrganizations/example.com/orderers/orderer1.example.com/tls/ca.crt

    orderer2.example.com:
        url: grpcs://192.168.56.51:7050

        grpcOptions:
            ssl-target-name-override: orderer2.example.com

        tlsCACerts:
            path: artifacts/crypto-config/ordererOrganizations/example.com/orderers/orderer2.example.com/tls/ca.crt

peers:
    peer0.org0.example.com:
        url: grpc://192.168.56.2:7051

        grpcOptions:
            ssl-target-name-override: peer0.org0.example.com
        tlsCACerts:
            path: artifacts/crypto-config/peerOrganizations/org0.example.com/peers/peer0.org0.example.com/tls/ca.crt

    peer1.org0.example.com:
        url: grpc://192.168.56.3:7051

        grpcOptions:
            ssl-target-name-override: peer1.org0.example.com
        tlsCACerts:
            path: artifacts/crypto-config/peerOrganizations/org0.example.com/peers/peer1.org0.example.com/tls/ca.crt

    peer2.org1.example.com:
        url: grpc://192.168.56.12:7051
        
        grpcOptions:
            ssl-target-name-override: peer2.org1.example.com
        tlsCACerts:
            path: artifacts/crypto-config/peerOrganizations/org1.example.com/peers/peer2.org1.example.com/tls/ca.crt

    peer3.org1.example.com:
        url: grpc://192.168.56.13:7051

        grpcOptions:
            ssl-target-name-override: peer3.org1.example.com
        tlsCACerts:
            path: artifacts/crypto-config/peerOrganizations/org1.example.com/peers/peer3.org1.example.com/tls/ca.crt
    
