name: "balance-transfer"

x-type: "hlfv1"

description: "Balance Transfer Network"

version: "1.0"

channels:
    ch1:
        orderers:
            - orderer0.example.com
            - orderer1.example.com
            - orderer2.example.com
        peers:
            peer0.org0.example.com:
                endorsingPeer: true
                chaincodeQuery: true
                ledgerQuery: true
                eventSource: true
            
            peer1.org0.example.com:
                endorsingPeer: false
                chaincodeQuery: true
                ledgerQuery: true
                eventSource: false
            
            peer0.org1.example.com:
                endorsingPeer: true
                chaincodeQuery: true
                ledgerQuery: true
                eventSource: true

            peer1.org1.example.com:
                endorsingPeer: false
                chaincodeQuery: true
                ledgerQuery: true
                eventSource: false

        chaincodes:
            - testnetCC:v0

organizations:
    Org0:
        mspid: Org0MSP

        peers:
            - peer0.org0.example.com
            - peer1.org0.example.com

        certificateAuthorities:
            - ca-org0

        adminPrivateKey:
            path: artifacts/crypto-config/peerOrganizations/org0.example.com/users/Admin@org0.example.com/msp/keystore/c058122b0740f7130ac8d1bfb07361bf2115e4498028602fac12b3deddba921e_sk
        
        signedCert:
            path: artifacts/crypto-config/peerOrganizations/org0.example.com/users/Admin@org0.example.com/msp/signcerts/Admin@org0.example.com-cert.pem

    Org1:
        mspid: Org1MSP
        
        peers:
            - peer0.org1.example.com
            - peer1.org1.example.com
        
        certificateAuthorities:
            - ca-org1

        adminPrivateKey:
            path: artifacts/crypto-config/peerOrganizations/org1.example.com/users/Admin@org1.example.com/msp/keystore/23c14d8afa36ac72ae058b450dd82ebd042f654f94b919861ae8ae7761424ca8_sk

        signedCert:
            path: artifacts/crypto-config/peerOrganizations/org1.example.com/users/Admin@org1.example.com/msp/signcerts/Admin@org1.example.com-cert.pem

orderers:
    orderer0.example.com:
        url: grpcs://13.124.214.129:7050
        
        grpcOptions:
            ssl-target-name-override: orderer0.example.com

        tlsCACerts:
            path: artifacts/crypto-config/ordererOrganizations/example.com/orderers/orderer0.example.com/tls/ca.crt
    
    orderer1.example.com:
        url: grpcs://15.164.187.242:7050

        grpcOptions:
            ssl-target-name-override: orderer1.example.com

        tlsCACerts:
            path: artifacts/crypto-config/ordererOrganizations/example.com/orderers/orderer1.example.com/tls/ca.crt

    orderer2.example.com:
        url: grpcs://13.209.27.139:7050

        grpcOptions:
            ssl-target-name-override: orderer2.example.com

        tlsCACerts:
            path: artifacts/crypto-config/ordererOrganizations/example.com/orderers/orderer2.example.com/tls/ca.crt

peers:
    peer0.org0.example.com:
        url: grpc://15.164.140.245:7051

        grpcOptions:
            ssl-target-name-override: peer0.org0.example.com
        tlsCACerts:
            path: artifacts/crypto-config/peerOrganizations/org0.example.com/peers/peer0.org0.example.com/tls/ca.crt

    peer1.org0.example.com:
        url: grpc://13.209.61.41:7051

        grpcOptions:
            ssl-target-name-override: peer1.org0.example.com
        tlsCACerts:
            path: artifacts/crypto-config/peerOrganizations/org0.example.com/peers/peer1.org0.example.com/tls/ca.crt

    peer0.org1.example.com:
        url: grpc://15.164.153.125:7051
        
        grpcOptions:
            ssl-target-name-override: peer0.org1.example.com
        tlsCACerts:
            path: crypto-config/peerOrganizations/org1.example.com/peers/peer0.org1.example.com/tls/ca.crt

    peer1.org1.example.com:
        url: grpc://15.164.121.13:7051

        grpcOptions:
            ssl-target-name-override: peer1.org1.example.com
        tlsCACerts:
            path: artifacts/crypto-config/peerOrganizations/org1.example.com/peers/peer1.org1.example.com/tls/ca.crt
    
certificateAuthorities:
    ca-org0:
        url: https://13.209.128.90:7054
        # the properties specified under this object are passed to the 'http' client verbatim when
        # making the request to the Fabric-CA server
        httpOptions:
            verify: false
        tlsCACerts:
            path: artifacts/crypto-config/peerOrganizations/org0.example.com/ca/ca.org0.example.com-cert.pem

        # Fabric-CA supports dynamic user enrollment via REST APIs. A "root" user, a.k.a registrar, is
        # needed to enroll and invoke new users.
        registrar:
            - enrollId: admin
              enrollSecret: adminpw
        # [Optional] The optional name of the CA.
        caName: ca-org0

    ca-org1:
        url: https://13.209.128.90:8054
        httpOptions:
            verify: false
        tlsCACerts:
            path: artifacts/crypto-config/peerOrganizations/org1.example.com/ca/ca.org1.example.com-cert.pem
        registrar:
            - enrollId: admin
              enrollSecret: adminpw
        # [Optional] The optional name of the CA.
        caName: ca-org1